### ISSUE TITLE
Just boots to command line

### ISSUE THREAD

**Issue by zburhop** [dupontgu/retro-ipod-spotify-client#21]
I have been over this very carefully and my ipod just boots to a command line.  I cant get it to run anything else.  Anyone have any ideas?

**Comment by HeartWaker000** [comment]
I can't make openbox auto run spotifypod.py either. In .bash_profile I can take the '-- - no cursor' argument out and then the black screen boots with a cursor. I can then right click on the black screen and open a terminal window from there where I can run python3 spotifypod.py . This will get the UI up and going and I can choose songs and play them etc. the only thing that fails is the search function. Maybe the search function needs another Scooe?

**Comment by zburhop** [comment]
quick question. where can i find .bash_profile  i created one in root but am wondering if that is not correct.

**Comment by HeartWaker000** [comment]
I believe it's correct. .bash_profile is a hidden file so it's probably in your root folder if you created it. Type ls -a in whatever directory you created .bash_profile in and you should see it. If you sudo nano .bash_profile you can edit the file your created.

**Comment by doctorleach** [comment]
I just discovered today the reason why my Pi wasn't entering the spotifypod.py program automatically on boot.  Although I set the environment for openbox to have my Spotify user id, secret and redirect URI, it didn't seem to be visible to the spotifypod.py script.  

The line
sudo -H -u pi python3 spotifypod.py &
executes the script as the user pi, but doesn't incorporate the environment for the pi user.  It is possible to pass a list of environment variables that do carry over when using sudo.  I'm not sure how others were able to boot into spotifypod.py, and I know some people couldn't, so if you're in the latter camp, here's what worked for me.

Here's how my /etc/xdg/openbox/autostart now reads:

cd /home/pi/retro-ipod-spotify-client/frontend/

sudo -H -u pi --preserve-env=SPOTIPY_REDIRECT_URI,SPOTIPY_CLIENT_ID,SPOTIPY_CLIENT_SECRET python3 spotifypod.py &

sudo /home/pi/retro-ipod-spotify-client/clickwheel/click &

**Comment by HerrEurobeat** [comment]
This works for me too! Great idea, I hadn't thought of the `--preserve-env` flag...

**Comment by zburhop** [comment]
`pi@raspberrypi:~$ cd /home/pi/home/pi/fork/retro-ipod-spotify-client/frontend
pi@raspberrypi:~/home/pi/fork/retro-ipod-spotify-client/frontend$ ls
datastore.py       pod_arrow_blk.ppm    pod_arrow_grn_2.bmp  pod_arrow_grn.png  pod_pause.png  pod_space.png  prog_frame.png  rand_circle.png  requirements.txt    spotifypod.py
pod_arrow_blk.png  pod_arrow_empty.png  pod_arrow_grn_2.png  pod_arrow_grn.ppm  pod_play.png   pod_wifi.png   __pycache__     README.md        spotify_manager.py  view_model.py
pi@raspberrypi:~/home/pi/fork/retro-ipod-spotify-client/frontend$ sudo python3 spotifypod.py
Traceback (most recent call last):
  File "spotifypod.py", line 12, in <module>
    from view_model import *
  File "/home/pi/home/pi/fork/retro-ipod-spotify-client/frontend/view_model.py", line 1, in <module>
    import spotify_manager
  File "/home/pi/home/pi/fork/retro-ipod-spotify-client/frontend/spotify_manager.py", line 79, in <module>
    sp = spotipy.Spotify(auth_manager=SpotifyOAuth(scope=scope))
  File "/usr/local/lib/python3.7/dist-packages/spotipy/oauth2.py", line 276, in __init__
    self.client_id = client_id
  File "/usr/local/lib/python3.7/dist-packages/spotipy/oauth2.py", line 92, in client_id
    self._client_id = _ensure_value(val, "client_id")
  File "/usr/local/lib/python3.7/dist-packages/spotipy/oauth2.py", line 71, in _ensure_value
    raise SpotifyOauthError(msg)
spotipy.oauth2.SpotifyOauthError: No client_id. Pass it or set a SPOTIPY_CLIENT_ID environment variable.
pi@raspberrypi:~/home/pi/fork/retro-ipod-spotify-client/frontend$ sudo -H -u pi --preserve-env=SPOTIPY_REDIRECT_URI,SPOTIPY_CLIENT_ID,SPOTIPY_CLIENT_SECRET python3 spotifypod.py
Enter the URL you were redirected to: http://127.0.0.0:8888
Enter the URL you were redirected to: no ints
`


So i cant get the spotifypod.py to run manually either.  It appears to be communicating with spotify but something is wrong with my credentials.  But all of that information is correct.  Any ideas?

**Comment by zburhop** [comment]
That post made a mess of the code.... i typed this .
pi@raspberrypi:~/home/pi/fork/retro-ipod-spotify-client/frontend$ sudo -H -u pi --preserve-env=SPOTIPY_REDIRECT_URI,SPOTIPY_CLIENT_ID,SPOTIPY_CLIENT_SECRET python3 spotifypod.py

and end up with it asking for 
Enter the URL you were redirected to: 
I type this http://127.0.0.0:8888 and it replys with this....
Enter the URL you were redirected to: no ints

**Comment by doctorleach** [comment]
OK, I think you actually are making good progress, because your program is communicating with Spotify.  

As an aside, I'm not sure it matters but you have 127.0.0.0 (probably an invalid address) whereas localhost is 127.0.0.1.  When you set up your project on the Spotify administration page, they asked you to type in the redirect URI.  Did you type in "http://127.0.0.0:8888" (without the quotes)?

Matching the URI exactly is very important.  Everywhere it appears, including in the /etc/xdg/openbox/environment file.

But back to the main story.  I think this is the point I got to before I installed a browser on the Pi Zero.  From your comments in the thread for Issue #22, however, I gather you did install Midori?  Do you have a .cache file in your frontend subdirectory where spotifypod.py is?

If you have Midori on the Pi, perhaps you should just open it and paste this in the URL box (substituting your correct credentials):

`https://accounts.spotify.com/authorize?client_id=XXX&response_type=code&redirect_uri=http%3A%2F%2F127.0.0.1&scope=user-read-playback-state%20user-modify-playback-state%20user-read-currently-playing%20app-remote-control%20streaming%20playlist-modify-public%20playlist-modify-private%20playlist-read-private%20playlist-read-collaborative%20user-library-modify%20user-library-read%20streaming` (replace XXX with client_id and make sure the redirect URI **exactly** matches the one in your Spotify project setup on spotify.com, although in this browser address box using URL escape codes like %3A for : and %2F for / )

I've been where you are now and I fought my way through.

**Comment by zburhop** [comment]
Oh i think i may get it now.  The screen started automatically taking me to the spotify page to login.  Maybe thats why VNC is recomended.  So i can authenticate there?  Im goning to try that now. Thanks for the help.

**Comment by zburhop** [comment]
So i setup VNC went in and tried to login to spotify as it requests it gives me a "there was an error please try again" meanwhile on the pc with the exact same username and password it logs in and out fine.  Ive rebooted and everything.  Is that not wierd?

**Comment by doctorleach** [comment]
I just noticed your comment (either you're up early for an American or you're in Europe).  I would suggest very carefully checking each occurrence of the REDIRECT_URI to make sure they are all absolutely identical. Also, look at the .cache file in the frontend subdirectory to see if it seems sensible; mine looks like this (incriminating details removed):

{"access_token": "[very long string of upper and lower case letters and numbers]", "token_type": "Bearer", "expires_in": 3600, "scope": "user-follow-read,user-library-read,user-library-modify,user-modify-playback-state,user-read-playback-state,user-read-currently-playing,app-remote-control,playlist-read-private,playlist-read-collaborative,playlist-modify-public,playlist-modify-private,streaming", "expires_at": 1615833272, "refresh_token": "[fairly long string of upper and lower case letters and numbers]"}

If yours looks like that but with random strings between the square brackets, then it is probably good.

You said you used VNC to go to the Pi Zero and "tried to login to spotify as it requests"--can you be more precise?  You ran the spotifypod.py script?  Did the browser come up?  Is that what you mean by login to Spotify?

Once you get a valid .cache access_token, the browser becomes irrelevant I think.

**Comment by zburhop** [comment]
Lol I like to work until like 5 am, you get a lot done when everyone is asleep.  I did check the uri and I did have it mismatched as you thought. But now it appears that the Spotifypod.py is now running at boot. The py  is now automatically loading the browser at the Spotify page asking me to login to Spotify for permissions. So I setup vnc to be able to do that from my desktop. The problem is that it will not let me login. It gives me an error. Not a password incorrect error but just a general error. I can login in my desktop no problem. I’m 100 percent certain I’ve got the right login credentials. Can you thing if a reason why Spotify would stop only the pi from logging in?

**Comment by doctorleach** [comment]
OK.  As you probably know, the spotifypod.py script runs at boot if you have the line:

sudo -H -u pi --preserve-env=SPOTIPY_REDIRECT_URI,SPOTIPY_CLIENT_ID,SPOTIPY_CLIENT_SECRET python3 spotifypod.py &

in the file /etc/xdg/openbox/autostart

and you can disable it for testing by commenting it out.

It calls the browser, though, which is progress.  You didn't tell me whether your .cache file exists in the retro-ipod-spotify-client/frontend directory and if it does whether it looks sorta like mine.  If you do have one and it looks nice, you might compare it to the one created on your desktop; you may even be able to copy it to the Pi, but that's just a guess.  

Maybe the fact that you logged in from your desktop is confusing Spotify.  Somebody else mentioned in some comment that you want to close any other instances of Spotify (including the client app) running on any other computers/phones/tablets so you might try that too.

Other than that, if everything checks out I would suggest looking through log files to see if there is a better description of the error.  If you disable the autostart of the spotifypod.py script on boot and run it from a terminal (in VNC so you are literally on the Pi), you might see some errors in the terminal.

If you have a Pi 4 you might want to do all this on it (put your SD card in it from the Zero) because things go much faster, although you wouldn't have the tiny display to give a fully realistic test.

I am listening to jazz on Spotify from my bluetooth speaker connected to my iPod/Spotipy splayed open on my desk.  So I'm sure you'll get there, hopefully soon.

**Comment by zburhop** [comment]
When I do "ls" the only cache file in that directory is a folder called __pycache__  It contains 3 .pyc files.  Other then that there are no other files relating to cache that I can see.

**Comment by doctorleach** [comment]
ls -a will show hidden files (those beginning with a . )

**Comment by zburhop** [comment]
aside from __pycache__ there is nothing else.

**Comment by zburhop** [comment]
I got spotify to authenticate in the web browser.  I linked my facebook to the spotify account.... then instead of using spotify themselves i elected to login via facebook and that worked.  The site popped up with authentication status : successful.  Before i close the window I'm sort of confused with what I'm supposed to do next. As this was not really documented in the github.

**Comment by doctorleach** [comment]
[your message just popped up when I was typing this:]

The __pycache__ subdirectory contains compiled byte code versions of the Python code that you ran, which is normal.  If you don't have a .cache file in frontend, then the authorization has not been given from Spotify, which is probably not news to you.

So the trick is to get the authorization.  If you disable the autostart and run spotifypod.py from a terminal (using VNC), I take it that the Midori browser (or whichever one you installed on the Pi) starts up and takes you to the accounts.spotify.com page?  And there are no errors shown in the terminal?  And you've shutdown any connections to Spotify you might have on other devices?

If still no clues,  grep librespot in /var/log/daemon.log

[ok, now for your latest message]

If you got the successful authentication, now run "ls -a" in the terminal in the frontend subdirectory and see if there is a .cache file

**Comment by doctorleach** [comment]
Although I'm a little nervous about the Facebook login angle . . . it's different from the methods discussed in these pages.

**Comment by zburhop** [comment]
It is kind of is news to me lol I expected I fixed it considering I have a giant page saying successful.

**Comment by doctorleach** [comment]
well check for .cache

if you have it then you shouldn't need the browser again, I think

**Comment by zburhop** [comment]
did ls-a and theres no .cache file

**Comment by zburhop** [comment]
Also my pi no longer boots to the web browser but instead is back to my old friend the empty black screen.

**Comment by doctorleach** [comment]
did you try pasting into the browser on the Pi:

https://accounts.spotify.com/authorize?client_id=XXX&response_type=code&redirect_uri=http%3A%2F%2F127.0.0.1&scope=user-read-playback-state%20user-modify-playback-state%20user-read-currently-playing%20app-remote-control%20streaming%20playlist-modify-public%20playlist-modify-private%20playlist-read-private%20playlist-read-collaborative%20user-library-modify%20user-library-read%20streaming 

(replace XXX with client_id and make sure the redirect URI exactly matches the one in your Spotify project setup on spotify.com, although in this browser address box using URL escape codes like %3A for : and %2F for / )

**Comment by doctorleach** [comment]
> Also my pi no longer boots to the web browser but instead is back to my old friend the empty black screen.

I would comment out the line in /etc/xdg/openbox/autostart that calls the script spotifypod.py

And it sounds like you are back to an authentication issue

**Comment by doctorleach** [comment]
By the way, are you still using the REDIRECT_URI http://127.0.0.0:8888 ?

**Comment by zburhop** [comment]
no im using http://127.0.0.1:8888

**Comment by zburhop** [comment]
so if i try to manually run it again its asks me "enter the Url you were redirected to:   what is it wanting from me here?

**Comment by doctorleach** [comment]
at some point mine just worked without asking me that; try http://127.0.0.1:8888

**Comment by doctorleach** [comment]
but it's probably not right

**Comment by zburhop** [comment]
That was my first instinct too. it replys no ints

**Comment by doctorleach** [comment]
ah, are either of these lines uncommented in view_model.py:

spotify_manager.refresh_devices()
spotify_manager.refresh_data()

**Comment by zburhop** [comment]
I only see refresh devices and it is uncommented

**Comment by doctorleach** [comment]
this is so annoying--I think you must be very close

**Comment by doctorleach** [comment]
when you were asked "enter the URL you were redirected to," what was showing in the browser URL box? If you can't remember, try running the python script again

**Comment by zburhop** [comment]
Its not graphical. That is via command line.  I type this.
sudo -H -u pi --preserve-env=SPOTIPY_REDIRECT_URI,SPOTIPY_CLIENT_ID,SPOTIPY_CLIENT_SECRET python3 spotifypod.py
and it replys with asking about the url

**Comment by doctorleach** [comment]
so the browser didn't open

**Comment by zburhop** [comment]
no the browser no longer opens.  Just black screen

**Comment by doctorleach** [comment]
if you execute in the terminal:

env | grep SPOTIPY

are the 3 SPOTIPY_ variables in there?

I suspect not, so you might want to run the 3 export commands from the terminal and try again

**Comment by doctorleach** [comment]
because if you execute the sudo line you just showed me it can't find the variables in the environment for the user pi

**Comment by zburhop** [comment]
there are but for some reason its picking up on 127.0.0.0:8002
not what i changed it all to http://127.0.0.1:8888  i bet theres multiple places and its getting it from somwehere else

**Comment by doctorleach** [comment]
try 

export SPOTIPY_REDIRECT_URI='http://127.0.0.1:8888'

**Comment by doctorleach** [comment]
I know my files at one point had http://127.0.0.1:8002, which is close to what you said, so you might have gotten it from me and miscopied it slightly; but who knows

**Comment by doctorleach** [comment]
you might also grep for 8002 in the frontend directory to see if it's in any script

**Comment by doctorleach** [comment]
also, check /etc/xdg/openbox/environment for the correct redirect uri

**Comment by zburhop** [comment]
so here's the deal. I used yours first and it didn't work so I switched to 8888 I have a bad habit of forgetting the 1.... so i guarantee i entered it wrong somewhere. its correct on spotifys developer site.  im trying to figure out all the places I was supposed to enter it on the pi.  Im definite i just messed the redirect up somewhere.

**Comment by doctorleach** [comment]
look to see if you added it to /home/pi/.bash_profile or some other configuration file in /home/pi

**Comment by zburhop** [comment]
Thats what i did. I fixed it.  Now when i run the 
sudo -H -u pi --preserve-env=SPOTIPY_REDIRECT_URI,SPOTIPY_CLIENT_ID,SPOTIPY_CLIENT_SECRET python3 spotifypod.py

it just says "no ints" over and over and over

**Comment by doctorleach** [comment]
so if you execute

env | grep SPOTIPY you get the 3 variables with correct values?

also add the line

spotify_manager.refresh_data()

to view_model_py and see if that makes a difference (I doubt it because of authorization failure)

and still no .cache?

try rebooting?

very frustrating

**Comment by zburhop** [comment]
yes 3 correct variables show up. Still no cache file.  Also very wierd view_model.py seems to be gone.....

**Comment by doctorleach** [comment]
your Pi is haunted

view_model.py is in the frontend subdirectory

and it doesn't normally disappear without being deleted

**Comment by doctorleach** [comment]
if you reboot and don't have spotifypod.py automatically execute, then you will probably have to export the 3 variables manually again

**Comment by zburhop** [comment]
Yeah i agree. when i do sudo nano its trying to create a new file

**Comment by doctorleach** [comment]
go have a drink and come back to it

**Comment by doctorleach** [comment]
get more sleep too

**Comment by zburhop** [comment]
I rebooted and tried again and it showed up... wierd but added the line and rebooted. Still black screen and no cache.  I am going to take a break.  Thanks so much for your help. I owe you one.  If you think of any more good ideas let me know.

**Comment by doctorleach** [comment]
ok, sorry we couldn't get there, but you must be close; probably some remnant file causing gremlins

**Comment by doctorleach** [comment]
Today I decided to install the project on a new SD card because rather than unsolder things on the pieces I already had lying around, I bought a Pi Zero without headers soldered in and an Adafruit Powerboost 1000 without connectors soldered in either, to try to finalize my iPod.  I did the installation on the SD card from my Pi 400, because it goes much faster.  But then I ran into just about all of the issues that have been plaguing @zburhop, including black screen, "Address in use" and "no int" repeated over and over.

I finally got it working, but I have to say I'm not completely sure what did the trick.  Even though I got these errors, at some point I decided to check if my .cache file had been written, and sure enough, it had been.  Frankly, I think this is the meshugaas (apparently the "official spelling") I went through the first time.

However--and I don't see why this would work--after I discovered I had the .cache file, the spotifypod.py script would run, but there would not be any songs to be seen (or heard).  I then wrote a very truncated copy of view_model.py that I named sync.py.  It only takes the first few lines (ending after the refresh_data() and refresh_devices() lines).  Running that script, I could see the messages printed to the command line, telling me it was downloading songs, playlists, etc.

From then on, the spotifypod.py script worked fine and the playlists, artists and album data was there.

I'll try to figure out from my notes and my history the last few things I tried before I got satisfaction, but it would seem that the order you do things in is very important.  Also, I did things like comment out the line in /etc/xdg/openbox/autostart that otherwise would start spotifypod.py automatically, and change the redirect URI several times--although each time I got the "Address in use" error.  Obviously it must have worked at least once, because I got the .cache file.
