### ISSUE TITLE
Debian Boot Screen with Errno98 Address Already in Use?

### ISSUE THREAD

**Issue by abou824** [dupontgu/retro-ipod-spotify-client#32]
About at my wits end here. Not sure where to go, here's my issue. My pi boots into a debian login screen. If I do enter my login information the prompt disappears and nothing else happens. This is all before I even login to the pi over ssh. When I run spotifypod.py, my output is as follows: 
`
Traceback (most recent call last):
  File "spotifypod.py", line 12, in <module>
    from view_model import *
  File "/home/pi/retro-ipod-spotify-client/frontend/view_model.py", line 17, in                                                  
<module>
    spotify_manager.refresh_data()
  File "/home/pi/retro-ipod-spotify-client/frontend/spotify_manager.py", line 15                                                 
9, in refresh_data
    results = sp.current_user_saved_tracks(limit=pageSize, offset=0)
  File "/home/pi/.local/lib/python3.7/site-packages/spotipy/client.py", line 122                                                 
6, in current_user_saved_tracks
    return self._get("me/tracks", limit=limit, offset=offset, market=market)
  File "/home/pi/.local/lib/python3.7/site-packages/spotipy/client.py", line 291                                                 
, in _get
    return self._internal_call("GET", url, payload, kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/spotipy/client.py", line 221                                                
 , in _internal_call
    headers = self._auth_headers()
  File "/home/pi/.local/lib/python3.7/site-packages/spotipy/client.py", line 212                                                
 , in _auth_headers
    token = self.auth_manager.get_access_token(as_dict=False)
  File "/home/pi/.local/lib/python3.7/site-packages/spotipy/oauth2.py", line 518                                                
 , in get_access_token
    "code": code or self.get_auth_response(),
  File "/home/pi/.local/lib/python3.7/site-packages/spotipy/oauth2.py", line 473                                                
 , in get_auth_response
    return self._get_auth_response_local_server(redirect_port)
  File "/home/pi/.local/lib/python3.7/site-packages/spotipy/oauth2.py", line 439                                                
 , in _get_auth_response_local_server
    server = start_local_http_server(redirect_port)
  File "/home/pi/.local/lib/python3.7/site-packages/spotipy/oauth2.py", line 130                                                 
3, in start_local_http_server
    server = HTTPServer(("127.0.0.1", port), handler)
  File "/usr/lib/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.7/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

I attached a picture of the debian screen as well. Sorry in advance if my code copy/paste is hard to read, this is literally my first github post haha. Thanks!! 
![20210414_210512](https://user-images.githubusercontent.com/82552592/114799270-3c11f680-9d65-11eb-850b-e55294bf422b.jpg)

`

**Comment by nassafellow** [comment]
Don't worry about it booting up like that.  Open your computer (Windows Powershell or Mac Terminal) follow the SSH process go to the sudo raspi-config and make sure it boots up as autologin console.  You'll be back to the good old command line and you won't need to enter a password either.

Learning myself...

**Comment by nassafellow** [comment]
Oh yeah, then restart using sudo reboot
