### ISSUE TITLE
Black screen issues & Raspotify - Pi Zero 1

### ISSUE THREAD

**Issue by TheBasedDoge** [dupontgu/retro-ipod-spotify-client#62]
Hi, Trying to get the project working on my Pi z W with waveshare screen. 

I followed the instructions in the readme, but I had to install the older version of raspotify:
raspotify_0.31.8.1.librespot.v0.3.1-54-gf4be9bb_armhf

First issue, on step 12 this file does not exist
sudo nano /etc/default/raspotify

However it does seem raspotify is running because I can see it as a a device in my spotify app. But not sure how to edit the config now.

Second issue: 
I get a black screen when the desktop loads, which then eventually crashes back to desktop. When i SSH in I get this:

xset:  unable to open display ""
xset:  unable to open display ""

When I try to run sudo -H -u pi python3 spotifypod.py I get this:

`
pi@pipod:~/retro-ipod-spotify-client/frontend$ sudo -H -u pi python3 spotifypod.py
Traceback (most recent call last):
  File "/home/pi/retro-ipod-spotify-client/frontend/spotifypod.py", line 12, in <module>
    from view_model import *
  File "/home/pi/retro-ipod-spotify-client/frontend/view_model.py", line 1, in <module>
    import spotify_manager
  File "/home/pi/retro-ipod-spotify-client/frontend/spotify_manager.py", line 102, in <module>
    sp = spotipy.Spotify(auth_manager=SpotifyOAuth(scope=scope))
  File "/home/pi/.local/lib/python3.9/site-packages/spotipy/oauth2.py", line 332, in __init__
    self.client_id = client_id
  File "/home/pi/.local/lib/python3.9/site-packages/spotipy/oauth2.py", line 94, in client_id
    self._client_id = _ensure_value(val, "client_id")
  File "/home/pi/.local/lib/python3.9/site-packages/spotipy/oauth2.py", line 70, in _ensure_value
    raise SpotifyOauthError(msg)
spotipy.oauth2.SpotifyOauthError: No client_id. Pass it or set a SPOTIPY_CLIENT_ID environment variable.
`

I did set the IDs in /etc/xdg/openbox/environment

Not sure what to do next

**Comment by TheBasedDoge** [comment]
I also realized that the paths changed for the newer raspotify, so i dropped it back down to an older version: raspotify_0.31.3.librespot.v0.3.1-19-gbbd575e_armhf.deb

I thought that would fix the issue but no. I also tried setting this up on a Pi 4 with a fresh install and same result

Traceback (most recent call last):
  File "spotifypod.py", line 12, in <module>
    from view_model import *
  File "/home/pi/retro-ipod-spotify-client/frontend/view_model.py", line 1, in <module>
    import spotify_manager
  File "/home/pi/retro-ipod-spotify-client/frontend/spotify_manager.py", line 102, in <module>
    sp = spotipy.Spotify(auth_manager=SpotifyOAuth(scope=scope))
  File "/home/pi/.local/lib/python3.7/site-packages/spotipy/oauth2.py", line 332, in __init__
    self.client_id = client_id
  File "/home/pi/.local/lib/python3.7/site-packages/spotipy/oauth2.py", line 94, in client_id
    self._client_id = _ensure_value(val, "client_id")
  File "/home/pi/.local/lib/python3.7/site-packages/spotipy/oauth2.py", line 70, in _ensure_value
    raise SpotifyOauthError(msg)
spotipy.oauth2.SpotifyOauthError: No client_id. Pass it or set a SPOTIPY_CLIENT_ID environment variable.


I set everything according to the instructions so I don't understand why i'm getting no client ID errors?

**Comment by Exploser** [comment]
were you able to fix this?
